
server:
  port: 8001
eureka:
  instance:
    instance-id: trying:authentication-server:test001 #发现客户端的实例id
    prefer-ip-address: true      #false 表示使用主机名进行地址访问；true表示根据IP进行地址重定向
  client:
    serviceUrl:
      defaultZone: http://192.168.1.208:8801/eureka/
spring:
  rabbitmq:
    host: 39.105.64.245
    port: 25672
    username: hchy
    password: 1qazxsw2


